name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-22.05
    - name: tests
      run: nix run ".#test"
    - name: Flake checks
      run: nix flake check
